// Auto-generated by manual i18n compiler
export const sourceLanguageTag = 'en' as const;
export const availableLanguageTags = ["de","en","es","fr","it","pl","pt","sk"] as const;
export type AvailableLanguageTag = typeof availableLanguageTags[number];

let currentLanguageTag: AvailableLanguageTag = sourceLanguageTag;

export const languageTag = (): AvailableLanguageTag => currentLanguageTag;

export const setLanguageTag = (tag: AvailableLanguageTag): void => {
  currentLanguageTag = tag;
  for (const listener of onSetLanguageTagListeners) {
    listener(tag);
  }
};

const onSetLanguageTagListeners: Array<(tag: AvailableLanguageTag) => void> = [];

export const onSetLanguageTag = (listener: (tag: AvailableLanguageTag) => void): void => {
  onSetLanguageTagListeners.push(listener);
};
